version: "3.8"

services:
  webd:
    build: .
    container_name: webd
    restart: unless-stopped
    ports:
      - "9212:9212"
    volumes:
      - ./data:/data
      - ./webd.conf:/etc/webd.conf:ro
